# This is a basic workflow to help you get started with Actions

name: Documentation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Building a jekyll site from configured directory, maybe deploying it.
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_ACTOR: "psyreactor"
          GITHUB_REPOSITORY: "psyreactor/sonarqube" 
          JEKYLL_ROOT: "docs/"
          DEPLOY_SITE: true 
        uses:  ileadall42/jekyll-build-optional-deploy-gh-pages@master
